### ISSUE TITLE
Support for uptodate dependencies

### ISSUE THREAD

**Issue by tehseengds** [ArunPrakashG/wordpress_client#16]
This package no longer supports up-to-date dependencies, so can you please update it

**Comment by ArunPrakashG** [comment]
@tehseengds 
My apologies for not maintaining the package for sometime. I have been pretty busy with my job and personal life.
I am planning to do rewrite some modules in the library, along with support for Dart 3 and refactoring. This however, could take some time.
Meanwhile, if you could push a PR with the updated packages, I will gladly review and merge it and then you could use the git URL in your pubspec to access the latest source.
