### ISSUE TITLE
example uses 'new'

### ISSUE THREAD

**Issue by sgehrman** [ArunPrakashG/wordpress_client#19]
WordpressClient client = new WordpressClient('https://www.replaceme.com/', 'wp-json/wp/v2');

new is obsolete.

**Comment by ArunPrakashG** [comment]
Hi,
I believe `new` isn't obsolete but just *optional*,
and you are right, the documentation requires an update. Currently pretty tied up with other stuff and Job. I will probably work on it when current work is settled down. Thanks for noticing!
