### ISSUE TITLE
why not one import?

### ISSUE THREAD

**Issue by sgehrman** [ArunPrakashG/wordpress_client#20]
I had to import

import 'package:wordpress_client/requests.dart';
import 'package:wordpress_client/responses.dart';
import 'package:wordpress_client/wordpress_client.dart';

why?

**Comment by ArunPrakashG** [comment]
Hi,
`requests.dart` & `responses.dart` files export numerous classes which otherwise, are not required in most of the files. The reason for splitting up these model classes is to reduce pollution in the intellisense dialog.
