### ISSUE TITLE
client.media.create is not working

### ISSUE THREAD

**Issue by plztrial4me** [ArunPrakashG/wordpress_client#28]
client.media.create is not working

**Comment by ArunPrakashG** [comment]
Hi @plztrial4me!
Thank you for taking your time to open an issue here.
I have deployed a fix for this and it should be live on pub.dev for download. The latest version is v8.0.5. Please upgrade and let me know your feedback!

Thank you!

**Comment by plztrial4me** [comment]
> Hi @plztrial4me! Thank you for taking your time to open an issue here. I have deployed a fix for this and it should be live on pub.dev for download. The latest version is v8.0.5. Please upgrade and let me know your feedback!
> 
> Thank you!

After upgrading to version 8.0.5 it works perfectly fine.

I didn't write in detail about the bug because I'm an old man who is not familiar with github, but thank you for fixing it quickly.

**Comment by ArunPrakashG** [comment]
@plztrial4me All good!
I was able to spot some issues with the codebase on review, it was pretty straightforward.
Again, thank you for letting me know of the case and have a good day!

Closing this issue as it is resolved.
