### ISSUE TITLE
Error when using tags.list()

### ISSUE THREAD

**Issue by plztrial4me** [ArunPrakashG/wordpress_client#30]
final response = await client.tags.list(ListTagRequest(perPage: 20));

or

final response = await client.tags.list(ListTagRequest(search: 'apple'));

In both cases above, the following error occurs.

```
Unhandled exception:
type 'int' is not a subtype of type 'String' of 'value'
#0      _LinkedHashMapMixin.[]= (dart:collection-patch/compact_hash.dart)
#1      MapExtensions.addIfNotNull (package:wordpress_client/src/utilities/extensions/map_extensions.dart:14:9)
#2      ListTagRequest.build (package:wordpress_client/src/requests/list/list_tag.dart:43:9)
#3      ListOperation.list (package:wordpress_client/src/operations/list.dart:8:37)
...
```

so I edit following two lines in package:wordpress_client/src/requests/list/list_tag.dart, then it works.
```
43:      ..addIfNotNull('page', page.toString())
44:      ..addIfNotNull('per_page', perPage.toString())
```

please, check it.

**Comment by ArunPrakashG** [comment]
@plztrial4me Hi there,
I have just pushed a new release onto pub.dev. Could you try out the latest build and let me know?
https://pub.dev/packages/wordpress_client

**Comment by plztrial4me** [comment]
> @plztrial4me Hi there, I have just pushed a new release onto pub.dev. Could you try out the latest build and let me know? https://pub.dev/packages/wordpress_client

Thanks! it works!
