### ISSUE TITLE
How can I update post's meta field?

### ISSUE THREAD

**Issue by plztrial4me** [ArunPrakashG/wordpress_client#34]
How can I update post's meta field?

UpdatePostRequest hasn't meta parameter.

**Comment by ArunPrakashG** [comment]
Hey @plztrial4me 
On #36 , i have added an option to pass additional arguments by using `extra` property on all requests. I think this should resolve your issue as you will be able to pass `meta` value via that property to the request.

**Comment by plztrial4me** [comment]
> Hey @plztrial4me On #36 , i have added an option to pass additional arguments by using `extra` property on all requests. I think this should resolve your issue as you will be able to pass `meta` value via that property to the request.

Thanks for resolving this quickly. It works!
