### ISSUE TITLE
Support for Linking and Embedding ?

### ISSUE THREAD

**Issue by rockyxcoded** [ArunPrakashG/wordpress_client#62]
Read more [https://developer.wordpress.org/rest-api/using-the-rest-api/linking-and-embedding](https://developer.wordpress.org/rest-api/using-the-rest-api/linking-and-embedding)

**Comment by ArunPrakashG** [comment]
Hey @rockyxcoded 

there is already a links field in all response objects. furthermore, you could handle this yourself by creating an extension on the response type that parses the `self` property to a custom class.

**Comment by rockyxcoded** [comment]
@ArunPrakashG Thanks for you response.

How about querying for embedded resource ?
[https://developer.wordpress.org/rest-api/using-the-rest-api/linking-and-embedding/#embedding](https://developer.wordpress.org/rest-api/using-the-rest-api/linking-and-embedding/#embedding)

**Comment by ArunPrakashG** [comment]
@rockyxcoded I have not tested this out yet. However, my only concern is if it will break the response parsing.

you can query by setting queryParameters property available in every request class.

to parse it, you use the self property on all responses.

**Comment by rockyxcoded** [comment]
@ArunPrakashG I don't think it will break the response parsing as it only adds and extra "_embedded" property to the response which can also be hanle in the Post response DTO.

I'll follow your recommendation for the mean time.

**Comment by ArunPrakashG** [comment]
@rockyxcoded, sure, i will work on the same once i am free. the approach i am most probably going to take is with an extension method that will expose the embeded field and links field, separated from the main response.
