### ISSUE TITLE
404 using Flutter Web ?

### ISSUE THREAD

**Issue by nah0y** [ArunPrakashG/wordpress_client#74]
Hello,

First, thanks a lot for the library :)

Running it on iOS/Mac/Android works totally fine, I have declared my baseUrl like so:
final baseUrl = Uri.parse('https://example.com/wp-json/wp/v2');
final client = WordpressClient(baseUrl: baseUrl);

But compiling on the web, I have 404 errors with links like:
GET https://example.com/media?page=1&per_page=100&order=desc 404 (Not Found)
GET https://example.com/categories?page=1&per_page=20&order=desc 404 (Not Found)
GET https://example.com/posts?page=1&per_page=100&order=desc 404 (Not Found)

The links are not example.com/wp-json/wp/v2... but example.com?

After creating my client, I log it with:
print("baseUrl: ${client.baseUrl} path: ${client.path} isReady: ${client.isReady}");
And I can see the correct data:
baseUrl: https://example.com/wp-json/wp/v2/ path: /wp-json/wp/v2/ isReady: true

Do you have any idea of what's going on?

Thanks :)

PS : The flutter web app is hosted directly on example.com, so maybe there's something going on with that?

**Comment by ArunPrakashG** [comment]
Hey @nah0y 
This is fixed on the latest version of the library. Please check it out and let me know!

`wordpress_client: ^8.5.3`

**Comment by nah0y** [comment]
Works like a charm!

You were super fast to find/fix the issue.

Thanks a lot :)
